apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres
  namespace: monitoring
type: Opaque
stringData:
  GF_DATABASE_PASSWORD: REPLACE_ME
  GF_DATABASE_USER: grafana
  GF_DATABASE_NAME: grafana
  GF_DATABASE_HOST: 10.77.0.14:5432
